authors = [
    "Dahua Lin <lindahua@gmail.com>",
    "John M Kuhn <jmkuhn@starpower.net>",
    "ScottPJones <scottjones@alum.mit.edu>",
    "Thomas Breloff <tom@breloff.com>",
    "Alex Arslan <ararslan@comcast.net>",
    "Chuan-Zheng Lee <czlee@stanford.edu>",
    "Galen Lynch <galen.lynch@gmail.com>",
    "Iain Dunning <iaindunning@gmail.com>",
    "Joseph Kleinhenz <kleinhenz.joseph@gmail.com>",
    "Keno Fischer <kfischer@college.harvard.edu>",
    "Kevin Squire <kevin@secondspectrum.com>",
    "Theodore Papamarkou <theodore.papamarkou@gmail.com>",
    "Tony Fong <tony.hf.fong@gmail.com>",
    "Tony Kelman <tony@kelman.net>",
    "Viral B. Shah <viral@mayin.org>",
    "Yichao Yu <yyc1992@gmail.com>",
    "odow <o.dowson@gmail.com>",
    "ranjanan <benditlikeranjan@gmail.com>"
    ]
desc = "C, Python, and type-defined numeric and string formatting"
keywords = ["Strings", "Formatting"]
license = "MIT"
name = "Format"
uuid = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"
version = "1.0.0"

[deps]
Compat  = "34da2185-b29b-5c13-b0c7-acf172513d20"

[compat]
julia = "^1.0.0"
Compat = "â‰¥ 1.0.1"
